name: LBLevels
version: '1.0'
main: lb.levels.main.MainLevels
api-version: 1.16
authors: [Dimensions]
depend:
  - LBEngines
commands:
  nivel:
    permission: lb.admin.level
    permission-message: "§cVocê não tem permissão para fazer isto."
  exp:
    permission: lb.admin.exp
    permission-message: "§cVocê não tem permissão para fazer isto."
